language: cpp
compiler:
  - gcc
  
# Setup repos etc before installation
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

script:
  - cd ./
  - make
